# Stage 1: Install & build
FROM node:18 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2: Serve
FROM node:18-alpine
WORKDIR /app

COPY --from=builder /app ./

RUN npm install --production

EXPOSE 3000
CMD ["npm", "run", "start"]
