version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: cv-c9-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - cv-c9-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: cv-c9-backend
    ports:
      - "8080:8080"
    restart: always
    networks:
      - cv-c9-network

networks:
  cv-c9-network:
    driver: bridge
